config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :people do
    collection do
      get :search
    end
  end
  resources :categories

  root 'people#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates_presence_of :name, message: "名称不能为空"
  validates_uniqueness_of :name, message: "该分类已存在"

  has_ancestry

  has_many :people
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :category

  validates_presence_of :number, :name, :sex, :age, :work_position, :title, :political_status, :education, :working_time, :come_university_time, :category_id,
                        messages: "不能为空"


  validates_uniqueness_of :number, messages: "该编码已存在"
  validates_numericality_of :age, :greater_than => 17, :less_than => 81


  def to_param
    "#{self.number}"
  end

  paginates_per 10

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_root_categories, only: [:new, :create, :edit, :update]
  before_action :find_category, only: [:edit, :update, :destroy]

  def index
    if params[:id].blank?
      @categories = Category.roots
    else
      @category = Category.find(params[:id])
      @categories = @category.children
    end

    @categories = @categories.order(id: "desc")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)

    if @category.save
      flash[:notice] = "保存成功"
      redirect_to categories_path
    else
      render action: :new
    end
  end

  def edit

  end

  def update

    if @category.update(categories_params)
      flash[:notice] = "修改成功"
      redirect_to categories_path
    else
      render action: :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:notice] = "删除成功"
      redirect_to categories_path
    else
      flash[:notice] = "删除失败"
      redirect_to :back
    end
  end

  private

  def find_root_categories
    @parent_categories = Category.roots.each { |c| c.ancestry = c.ancestry.to_s + (c.ancestry != nil ? "/" : '') + c.id.to_s
      }.sort {|x,y| x.ancestry <=> y.ancestry
      }.map{ |c| ["-" * (c.depth - 1) + c.name,c.id]
      }.unshift(["-- none --", nil])
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def categories_params
    params.require(:category).permit!
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :find_person, only: [:edit, :update, :destroy]

  def index
    @people = Person.all.includes(:category).page params[:page]
    @all_people_count = Person.all.count
    # 按人员类别分类
    if params[:category].present?
      @category = Category.find(params[:category])
      if @category.root? && @category.has_children?
        @categories = @category.children
        @people = @people.where(:category => @categories)
      else
        @people = @people.where(:category => @category)
      end
    end



    # 按 年龄/来院时间 排序
    @people = case params[:order]
      when "按年龄降序排序"
        @people.order("age DESC").page params[:page]
      when "按年龄升序排序"
        @people.order("age ASC").page params[:page]
      when "按来院时间降序排序"
        @people.order("come_university_time DESC")
      when "按年龄升序排序"
        @people.order("come_university_time ASC")
      else
        @people
    end

  end

  def edit

  end

  def update
    if @person.update(person_params)
      redirect_to people_path
      flash[:notice] = "成功更新人员信息"
    else
      render "edit"
    end
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path
      flash[:notice] = "成功添加新人员"
    else
      render "new"
    end

  end

  def destroy
    @person.destroy
    redirect_to people_path
    flash[:alert] = "成功删除人员"
  end

  def search
    @people = Person.where("number = ? OR name = ?", params[:search_message], params[:search_message]).page params[:page]

    render file: 'people/index'
  end

  private

  def find_person
    @person = Person.find_by_number(params[:id])
  end

  def person_params
    params.require(:person).permit!
  end



end

app/helpers/application_helper.rb
module ApplicationHelper


  def choose_category
    unless category.root?
      f.association :category, label: "人员分类", error: "不能为空"
    else

    end
  end

end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def people_filiters(options)
    params.permit(:category, :order).merge(options)
  end


  def category_people_count(category)
    count = 0
    if category.root? && category.has_children?
      category.children.each do |c|
        count += c.people.size
      end
    else
      count = category.people.size
    end
    "#{category.name}" + " ( " + count.to_s + "人 )"
  end

  def render_category_list(category)
    unless category.root?
      link_to(category_people_count(category), people_path(people_filiters(:category => category)), style:"margin-left:10px" )
    else
      link_to(category_people_count(category), people_path(people_filiters(:category => category)) )
    end
  end

end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <label for="ancestry" class="control-label">名称:</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="ancestry" class="control-label">所属分类:</label>
    <%= f.select :parent_id, @parent_categories, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "保存", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<main>
  <div class="container, col-md-offset-4 col-md-3">
    <%= render 'form' %>
  </div>
</main>

app/views/categories/index.html.erb
<main>
  <div class="pull-right">
    <%= link_to "新建分类", new_category_path, class: "btn btn-primary" %>
  </div>
  <div class="">
    <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>名称</th>
        <th></th>
      </tr>

      <% @categories.each do |category| %>
        <tr>
          <td><%= category.id %></td>
          <td><%= category.name %></td>
          <td align="right">
            <%= link_to "编辑", edit_category_path(category) %>
            <%= link_to "删除", category_path(category), method: :delete, 'data-confirm': "确认删除吗?" %>
            <% if category.children? %>
              <%= link_to "查看子分类", categories_path(id: category) %>
            <% end -%>
          </td>
        </tr>
      <% end -%>
    </table>
  </div>
</main>

app/views/categories/new.html.erb
<main>
  <div class="container, col-md-offset-4 col-md-3">
    <%= render 'form' %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatabaseClassHomework</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "shared/header" %>
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/people/_form.html.erb
<%= simple_form_for @person do |f| %>


  <%= f.input :number, label: "人员编号", error: "输入为空字符或该编号已存在" %>
  <%= f.input :name, label: "姓名", error: "不能为空" %>


  <%= f.association :category, label: "人员分类", error: "不能为空" %>
  <%= f.input :sex, collection: ["男","女"], label: "性别", error: "不能为空" %>

  <%= f.input :age, label: "年龄", error: "输入为空或超出范围（18 ~ 80）" %>
  <%= f.input :work_position, label: "职位", error: "不能为空" %>
  <%= f.input :title, label: "职称", error: "不能为空" %>
  <%= f.input :political_status, collection: ["群众","团员","党员"], label: "政治面貌", error: "不能为空" %>
  <%= f.input :education, collection: ['专科','本科','硕士','博士'], selected: "本科", label: "最高学历", error: "不能为空" %>

  <%= f.input :working_time, label: "任职时间", error: "不能为空" %>
  <%= f.input :come_university_time, label: "来院时间", error: "不能为空" %>

  <%= f.button :submit, @person.new_record? ? "新建人员" : "编辑人员" %>
<% end %>

app/views/people/_people_menu.html.erb
<div class="pull-right">
  <%= link_to "添加人员", new_person_path, class: "btn btn-primary" %>
</div>

<br>
<div>

  <%= form_tag search_people_path, class:"navbar-form navbar-left", method: :get do %>
    <input type="text" name="search_message" value="<%= params[:search_message] %>" class="form-control search-input"
      placeholder="输入姓名或者编号" required>
    <button type="submit" class="btn btn-default">搜索</button>
  <% end %>

  <!-- 排序方式 -->
  <div class="dropdown btn-group sift-menu">
    <% if params[:order].present? %>
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= params[:order] %> <span class="caret"></span>
      </button>
    <% else %>
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
         默认 <span class="caret"></span>
      </button>
    <% end %>

    <ul class="dropdown-menu">
      <li><%= link_to("默认排序", people_path( people_filiters( :order => "" ) )) %></li>
      <li><%= link_to("按年龄降序排序", people_path( people_filiters(:order => "按年龄降序排序") ))%></li>
      <li><%= link_to("按年龄升序排序", people_path( people_filiters(:order => "按年龄升序排序") ))%></li>
      <li><%= link_to("按来院时间降序排序", people_path( people_filiters(:order => "按来院时间降序排序") ))%></li>
      <li><%= link_to("按来院时间升序排序", people_path( people_filiters(:order => "按来院时间降序排序") ))%></li>
    </ul>
  </div>

  <!-- 分类筛选 -->
  <div class="dropdown btn-group clearfix sift-menu">
    <% if params[:category].present? %>
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= category_people_count(@category) %> <span class="caret"></span>
      </button>
    <% else %>
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
         所有人员 ( <%= @all_people_count %>人 ) <span class="caret"></span>
      </button>
    <% end %>

    <ul class="dropdown-menu">
        <li><%= link_to("所有人员( #{ @all_people_count}人 )", people_path( people_filiters( :category => "" ) )) %></li>
      <% Category.find_each do |category| %>
        <li>
          <%= render_category_list(category) %>
        </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/people/_person_item.html.erb
<tr>
  <td><%= person.number %></td>
  <td><%= person.name %></td>
  <td><%= person.category.name %></td>
  <td><%= person.sex %></td>
  <td><%= person.age %></td>
  <td><%= person.work_position %></td>
  <td><%= person.title %></td>
  <td><%= person.political_status %></td>
  <td><%= person.education %></td>
  <td><%= person.working_time.strftime("%Y/%m/%d") %></td>
  <td><%= person.come_university_time.strftime("%Y/%m/%d") %></td>
  <td align="right">
    <%= link_to "编辑", edit_person_path(person) %>
    <%= link_to "删除", person_path(person), method: :delete, 'data-confirm': "确认删除吗?" %>
  </td>
</tr>

app/views/people/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <%= render 'form' %>
</div>

app/views/people/index.html.erb
<%= render "people/people_menu" %>
<table class="table">
  <tr style="background-color: gray">
    <th>编号</th>
    <th>名称</th>
    <th>人员类别</th>
    <th>性别</th>
    <th>年龄</th>
    <th>职务</th>
    <th>职称</th>
    <th>政治面貌</th>
    <th>最高学历</th>
    <th>任职时间</th>
    <th>来院时间</th>
    <th></th>
  </tr>

  <%= render partial: "person_item", collection: @people, as: :person %>

</table>
<div class="text-center">
  <%= paginate @people, window: 1, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/people/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <%= render 'form' %>

</div>


<script type="text/javascript">
  $(document).ready(function(){
    $("#person_category_id option[value='1']").attr("disabled","disabled"); //有子分类的root分类设为disabled

    //子分类加上 "---"
    var i = 2;
    function modifySub(a){
      temp = $('#person_category_id option[value=' + a + ']');

      temp_text = temp.text()
      temp.text("---- " + temp_text);
    }

    while(i < 4){
      alertSub(i);
      i++;
    }

  })


</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.messages.values.flatten.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container" style="margin-top: 50px;">
    <br>
    <p style="text-align:center;">
      Desgin by 李武钊
    </p>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">教务管理系统</a>
    </div>
  </div>
</nav>